#! /bin/zsh

# Ask the user for permission to destroy the existing instance 
read "destroy?Are you OK with destroying the site instance found in ./prussianblue? [Y/n]"
case $destroy in
  [nN][oO]|[nN])
    echo "Ok. No destruction, no construction. Aborting the mission."
    exit 0
    ;;
  [yY][eE][sS]|[yY]|"")
    echo "Yeehaw! [grabs sledgehammer]"
    ;;
esac

if [ -d "prussianblue" ]; then
  echo "Destroying the DDEV instance and ommitting snapshots."
  existing=`cat prussianblue/instance-id`
  ddev delete $existing --omit-snapshot --yes

  echo "Deleting the files"
  rm -rf prussianblue
fi

